---
# handlers file for apparmor
- name: Set all apparmor profiles to complain
  command: find /etc/apparmor.d/ -type d -exec aa-complain {} \;
  listen: apparmor installed
- name: regenerate grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
  notify: reboot machine
- name: reboot machine
  reboot:
  when: "{{ apparmor_allow_reboot | bool }}"
