---
# handlers file for apparmor
- name: Add apparmor variables to GRUB
  lineinfile:
    dest: /etc/default/grub
    state: present
    backrefs: "{{ item.backrefs }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "{{ item.insertbefore }}"
  with_items:
    - regexp: '^GRUB_CMDLINE_LINUX_APPARMOR='
      line: 'GRUB_CMDLINE_LINUX_APPARMOR="apparmor=1 security=apparmor"'
      insertbefore: '^GRUB_CMDLINE_LINUX='
      backrefs: no
    - regexp: '^GRUB_CMDLINE_LINUX="((?!\$GRUB_CMDLINE_LINUX_APPARMOR).*)$'
      line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX_APPARMOR \1'
      insertbefore: ''
      backrefs: yes
  listen: apparmor installed
  notify: regenerate grub
- name: Set all apparmor profiles to complain
  command: find /etc/apparmor.d/ -type d -exec aa-complain {} \;
  listen: apparmor installed
- name: regenerate grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
  notify: reboot machine
- name: reboot machine
  reboot:
  when: "{{ apparmor_allow_reboot | bool }}"
